#注意：如果在记事本上编写，下面的缩进不能按tab键，不然报错
spring:
  profiles:
    active: dev #激活开发环境配置
---
server:
  port: 6001 #端口号
spring:
  profiles: dev #开发环境
  application:
    name: microservice-product-eureka  #服务名

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegisty: false
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，集群版配置对方地址，单机版配置自己(如果不配置，则默认本机8761端口)
      defaultZone: http://eureka6001.com:6001/eureka/
  server:
    enable-self-preservation: false  #禁用自我保护
---
server:
  port: 6001 #端口号
spring:
  profiles: prod #生产环境
  application:
    name: microservice-product-eureka  #服务名

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegisty: false
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，集群版配置对方地址，单机版配置自己(如果不配置，则默认本机8761端口)
      defaultZone: http://eureka6001.com:6001/eureka
  server:
    enable-self-preservation: true  #开启自我保护
      
#保存时注意选择UTF-8保存
